optimized cooldown period
Sperax/Demeter-Protocol pull request #45
Opened 2024-02-15 13:45 UTC by TechnoGeek01

2024-02-15 14:07 UTC, parv3213 approved these changes
The full gas report does not look much improved, but I still support this refactor.

2024-02-16 11:57 UTC, arcantheon approved these changes

2024-02-20 08:12 UTC, parv3213 approved these changes

2024-02-20 14:14 UTC, YashP16 requested changes

2024-02-21 07:17 UTC, parv3213 approved these changes

2024-02-21 07:34 UTC, YashP16 approved these changes

2024-02-22 09:32 UTC, parv3213 approved these changes

2024-02-22 09:41 UTC, bayou020 approved these changes

2024-02-22 12:24 UTC, merged