Enabling fixed APR reward tokens for Demeter Protocol
Sperax/Demeter-Protocol pull request #50
Opened 2024-02-26 12:05 UTC by arcantheon

2024-03-04 12:13 UTC, YashP16 requested changes

2024-03-04 12:13 UTC, YashP16 commented on contracts/e20-farms/E20Farm.sol
> +
This could be an abstract farm right?

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +        _transferOwnership(msg.sender);
Transferring the ownership to rewarder factory!

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +        _validateFarm(_farm);
Should also check if this includes the required base tokens

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +        address _oracle = IRewarderFactory(rewarderFactory).oracle();
just use oracle?

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +        _validateFarm(_farm);
Just check if the farm is linked with reward token instead of this.

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +            (address[] memory _assets, uint256[] memory _amounts) = IFarm(_farm).getTokenAmounts();
don't use `_` for temporary variables unless clashes with state variables.

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +            if (_assetsLen == _amounts.length) {
Why is this check required?

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +                rewardsToSend = (rewardsPerSecond * 1 weeks);
define a constant for 1 weeks -> `REWARD_PERIOD`

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +                        rewardsPerSecond = (_farmRwdBalance + _rewarderRwdBalance) / 1 weeks;
This is not required. 
rewardsPerSec should be purely calculated based on the APR. 

If there is not enough Reward in the rewarder, funds will simply exhaust.

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +                _adjustGlobalRewardsPerSec(farmRewardConfig.rewardsPerSec, rewardsPerSecond);
instead of using rewardsPerSecond, noLockupRewardPer ....
use rewardRate, noLockupRewardRate

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/Rewarder.sol
> +        uint8 _decimals = ERC20(_token).decimals();
should we just cache this here in the contract itself? 
we can keep mapping(address => uint8) decimals and fetch only if decimals[token] = 0

2024-03-04 12:13 UTC, YashP16 commented on contracts/rewarder/RewarderFactory.sol
> +        rewarderInstance.initialize(_rwdToken, oracle);
validating the price feed here itself will save some gas

2024-03-04 12:13 UTC, YashP16 commented on contracts/utils/TokenUtils.sol
> +        amounts[0] = (_farmLiquidity * reserveA) / _totalSupply;
do we need to normalize amounts here?

2024-03-04 12:13 UTC, YashP16 commented on contracts/utils/TokenUtils.sol
> +        amounts[0] = (_farmLiquidity * reserveA) / _totalSupply;
this might be also pre-considered in the calculations, please check

2024-03-04 12:13 UTC, YashP16 commented on contracts/interfaces/IFarmRegistry.sol
> +    function farmRegistered(address farm) external view returns (bool);
do we need this check?

2024-03-05 12:05 UTC, arcantheon commented on contracts/interfaces/IFarmRegistry.sol
> +    function farmRegistered(address farm) external view returns (bool);
Removed: ecd3155ae8c7ef3eb03568f37f60316292c5f0ae

2024-03-05 12:10 UTC, arcantheon commented on contracts/utils/TokenUtils.sol
> +        amounts[0] = (_farmLiquidity * reserveA) / _totalSupply;
We do not need to normalize here because it is handled in the rewarder, because getTokenAmounts can be called at other places as well to get the underlying amounts, if we normalize it here we would only be able to use getTokenAmounts in rewarder and nowhere else.

2024-03-05 12:18 UTC, arcantheon commented on contracts/rewarder/RewarderFactory.sol
> +        rewarderInstance.initialize(_rwdToken, oracle);
If we do it here, we will have to add validation logic, custom error here as well. Which is already there in Rewarder.sol. Sure we will save some gas but we will deploy redundant code on the blockchain. Hence I feel it is okay to keep it like this. If you still feel we should change it, please comment below.

2024-03-05 12:24 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +        _transferOwnership(msg.sender);
Updated: 4012a0e56ab6cdc2c5eb5562b8807146aa5e99ad

2024-03-05 12:32 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +        uint8 _decimals = ERC20(_token).decimals();
Good idea, implemented: 362a53dbdc199532fab9edac7c5fa91ba42a3931

2024-03-05 13:43 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +        _validateFarm(_farm);
Refactored: 862b679449a4d701452bdffab91d99e3f1e5c023

I have update the logic to validate farm. Now it checks both of the things only while setting the reward config. So no need to check again while calibrating.

2024-03-05 13:43 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +            if (_assetsLen == _amounts.length) {
Removed: 862b679449a4d701452bdffab91d99e3f1e5c023

2024-03-05 13:44 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +                        rewardsPerSecond = (_farmRwdBalance + _rewarderRwdBalance) / 1 weeks;
Removed: f9bee69c306f0a4e6e55c9daf49632ad27df6f46

2024-03-05 13:55 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +                _adjustGlobalRewardsPerSec(farmRewardConfig.rewardsPerSec, rewardsPerSecond);
noLockupRewardPer is not noLockupRewardRate it is noLockupRewardPercentage instead of noLockupRewardPerSec.

Updated rewardsPerSecond -> rewardRate: 54d9e57f3b9217ea1083678290f4cc91ba0debd5

2024-03-05 13:55 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +                rewardsToSend = (rewardsPerSecond * 1 weeks);
Added: 54d9e57f3b9217ea1083678290f4cc91ba0debd5

2024-03-05 13:55 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +            (address[] memory _assets, uint256[] memory _amounts) = IFarm(_farm).getTokenAmounts();
Updated: 54d9e57f3b9217ea1083678290f4cc91ba0debd5

2024-03-05 13:57 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +        address _oracle = IRewarderFactory(rewarderFactory).oracle();
If we have to change the Oracle, we will have to change it in all the rewarders (multiple calls) + and we are not tracking the rewarders so we will not even know where all we have to update, so that is why fetching from the RewarderFactory

2024-03-05 15:12 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +        _validateFarm(_farm);
Added: 09e9df4d0c022df57713e04390818e33c9664e08

2024-03-05 15:13 UTC, arcantheon commented on contracts/e20-farms/E20Farm.sol
> +
No, this can be used as a Balancer farm, if we make this abstract will have to add a new balancer farm.

2024-03-05 15:24 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +        address _oracle = IRewarderFactory(rewarderFactory).oracle();
naming convention comment

2024-03-05 15:56 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +        address _oracle = IRewarderFactory(rewarderFactory).oracle();
Updated: 6c51db19ea65493e481a70cd2749ea8d881ee6b9

2024-03-05 16:07 UTC, arcantheon commented on contracts/e20-farms/E20Farm.sol
> +
Made it abstract here: dd8ca7ea00f390b4d2ca4d3bb3d2f5b5d246a7f4

2024-03-07 10:27 UTC, YashP16 requested changes

2024-03-07 10:27 UTC, YashP16 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateRewardConfig(address _farm, FarmRewardConfig memory _rewardConfig) external onlyOwner {
@arcantheon , create another input type that doesn't have the reward rate as a required input.
That would be much cleaner

2024-03-07 10:27 UTC, YashP16 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +        if (_decimals[_token] != 18) {
no need of this check

2024-03-07 10:27 UTC, YashP16 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +                for (uint8 jBaseTokens; jBaseTokens < baseTokensLen;) {
given that we already validate the base token in the farm, 
I think we can also cache the baseToken index in Farm token. 

This is again with an assumption that the index farm token index doesn't change, but that won't happen I think.

2024-03-07 10:27 UTC, YashP16 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +                for (uint8 jBaseTokens; jBaseTokens < baseTokensLen;) {
we can cache the index while validating the config on update itself.

2024-03-08 13:24 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +        if (_decimals[_token] != 18) {
Removed: 4d829f133c88461c2e3ad3e7daf02d77f9ea583e

2024-03-08 13:24 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateRewardConfig(address _farm, FarmRewardConfig memory _rewardConfig) external onlyOwner {
Done: 4d829f133c88461c2e3ad3e7daf02d77f9ea583e

2024-03-09 12:49 UTC, TechnoGeek01 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +        totalRewardRate += _newRewardRate;
we can do this in a single line.

Also x=x+y costs less gas than x+=y for normal state variables (not applicable for mappings, structs, etc).

Suggestion -> `totalRewardRate = totalRewardRate - _oldRewardRate + _newRewardRate;`

2024-03-09 13:12 UTC, TechnoGeek01 commented on contracts/utils/TokenUtils.sol
> +            IUniswapV3Utils(_uniUtils).getAmountsForLiquidity(sqrtPriceX96, _tickLower, _tickUpper, uint128(_liquidity));
We are using spot price of a pool for calculation. Is this fine?

2024-03-11 08:14 UTC, parv3213 reviewed
There are a few solhint warnings, please address them.

2024-03-11 08:14 UTC, parv3213 commented on contracts/e20-farms/balancerV2/BalancerV2Farm.sol
> +        revert NotImplemented();
This is intended?

2024-03-11 08:14 UTC, parv3213 commented on contracts/e721-farms/uniswapV3/UniV3Farm.sol
> +            uniswapPool, uniswapUtils, tickLowerAllowed, tickUpperAllowed, rewardFunds[COMMON_FUND_ID].totalLiquidity
We only consider the COMMON_FUND_ID, and not the lockup funds. It this intended?

2024-03-11 08:24 UTC, YashP16 commented on contracts/utils/TokenUtils.sol
> +            IUniswapV3Utils(_uniUtils).getAmountsForLiquidity(sqrtPriceX96, _tickLower, _tickUpper, uint128(_liquidity));
Good point. There is a chance of this being manipulated.
Someone can do a sandwich call to calibrate rewards, 
first updating the poolPrice -> calibrateRewards -> revert poolPrice.

2024-03-11 08:25 UTC, YashP16 commented on contracts/e20-farms/balancerV2/BalancerV2Farm.sol
> +        revert NotImplemented();
I think computing values for balancer is slightly complex so we are skipping for now.

2024-03-11 08:26 UTC, YashP16 commented on contracts/e721-farms/uniswapV3/UniV3Farm.sol
> +            uniswapPool, uniswapUtils, tickLowerAllowed, tickUpperAllowed, rewardFunds[COMMON_FUND_ID].totalLiquidity
All the liquidity that is provided in the pool shares the rewards from common_fund.

2024-03-11 08:37 UTC, arcantheon commented on contracts/utils/TokenUtils.sol
> +            IUniswapV3Utils(_uniUtils).getAmountsForLiquidity(sqrtPriceX96, _tickLower, _tickUpper, uint128(_liquidity));
How can we prevent this?

2024-03-11 08:39 UTC, arcantheon commented on contracts/e721-farms/uniswapV3/UniV3Farm.sol
> +            uniswapPool, uniswapUtils, tickLowerAllowed, tickUpperAllowed, rewardFunds[COMMON_FUND_ID].totalLiquidity
Yes, because people may or may not have liquidity in the lockup fund but their liquidity will be tracked in common fund for rewards.

2024-03-11 09:10 UTC, parv3213 commented on contracts/Farm.sol
Changes made in this file should ideally we tested in Farm.t.sol

2024-03-11 09:10 UTC, parv3213 commented on contracts/Farm.sol
> +    error NotImplemented();
Only used in BalanceV2Farm. Consider moving it there itself.

2024-03-11 09:10 UTC, parv3213 commented on contracts/Farm.sol
> +        return rewardTokens;
`rewardTokens` is already a public variable that returns `address[] memory`. Why do we need this additional function? If we really need `getRewardTokens` consider making `rewardTokens` internal.

2024-03-11 09:10 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +interface ICamelotFarm {
Better to move these interface to a separate file.

2024-03-11 09:10 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    struct FarmRewardConfigParams {
FarmRewardConfigInput maybe a better naming convention

2024-03-11 09:10 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    address public constant REWARD_TOKEN = 0x5575552988A3A80504bBaeB1311674fCFd40aD4B;
Lets not take hardcoded addressed. Take these in params.

2024-03-11 09:10 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    string public constant CAMELOT_FARM_ID = "Demeter_Camelot_v1";
Where do we use this?

2024-03-11 09:10 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    error FarmNotSupported();
Not used anywhere

2024-03-11 09:10 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    error InvalidFarm();
Not used anywhere

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateRewardConfig(address _farm, FarmRewardConfigParams memory _rewardConfig) external onlyOwner {
Add nonReentrant?

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateTokenManagerInFarm(address _farm, address _newManager) external onlyOwner {
```suggestion
    function updateTokenManagerOfFarm(address _farm, address _newManager) external onlyOwner {
```

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateTokenManagerInFarm(address _farm, address _newManager) external onlyOwner {
Or updateFarmTokenManager`

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +        FarmRewardConfig memory farmRewardConfig = farmRewardConfigs[_farm];
Storage variables are generally cheaper.

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +            IOracle.PriceData memory _priceData;
`_priceData` to `priceData`

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +                (((farmRewardConfig.apr * totalValue) / (APR_PRECISION * 100)) / 365 days) * _priceData.precision
instead of 100 and 365 days, store them in a constant and use that instead. Also what is 100 here for?

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +            rewardsToSend = (rewardRate * REWARD_PERIOD);
```suggestion
            rewardsToSend = rewardRate * REWARD_PERIOD;
```

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function calibrateRewards(address _farm) public returns (uint256 rewardsToSend) {
Add nonReentrant

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +            _setRewardRate(_farm, rewardRate, farmRewardConfig.noLockupRewardPer);
```
_setRewardRate(_farm, rewardRate, farmRewardConfig.noLockupRewardPer);
            _adjustGlobalRewardRate(farmRewardConfig.rewardRate, rewardRate);
            farmRewardConfigs[_farm].rewardRate = rewardRate;
            emit RewardsCalibrated(_farm, rewardsToSend, rewardRate);
            ```
can be moved out of if/else. Only `rewardRate` `rewardsToSend` needs to be different based on conditions.

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function getTokenAmounts(address _farm) public view returns (address[] memory assets, uint256[] memory amounts) {
nonReentrant?

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    /// @param _noLockupRewardPer Reward percentage to be allocated to no lockup fund
I recommend, `_noLockupRewardPer` -> `_nonLockupRewardPer`

2024-03-11 10:03 UTC, parv3213 commented on contracts/rewarder/Rewarder.sol
> +    address public REWARD_TOKEN;
Should not be in All-Caps.

2024-03-11 10:05 UTC, parv3213 commented on contracts/rewarder/RewarderFactory.sol
> +    /// @notice Contructor of this contract.
```suggestion
    /// @notice Constructor of this contract.
```

2024-03-11 12:52 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +                for (uint8 jBaseTokens; jBaseTokens < baseTokensLen;) {
Updated: 52fe76a9c766190c089917efc641b99e3662e034

2024-03-12 05:30 UTC, arcantheon commented on contracts/Farm.sol
> +    error NotImplemented();
Moved: d898cc59389e949631d31e18e4d8e41ff137f76b

2024-03-12 05:31 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +interface ICamelotFarm {
Moved: d898cc59389e949631d31e18e4d8e41ff137f76b

2024-03-12 05:31 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    struct FarmRewardConfigParams {
Renamed: d898cc59389e949631d31e18e4d8e41ff137f76b

2024-03-12 07:30 UTC, TechnoGeek01 commented on contracts/rewarder/Rewarder.sol
> +    }
same suggestion as comment https://github.com/Sperax/Demeter-Protocol/pull/50#discussion_r1518568614

Suggestion -> `totalRewardRate = totalRewardRate - _oldRewardRate + _newRewardRate;`

2024-03-12 08:02 UTC, arcantheon commented on contracts/Farm.sol
> +        return rewardTokens;
The function you are suggesting does not return `address[] memory` rather it accepts an index and returns the reward token's `address` at that index. So we need this function to return the whole array at once.

We need this function in rewarder to check whether the reward token (rewarder) is a reward token in the farm or not.

2024-03-12 08:13 UTC, arcantheon commented on contracts/Farm.sol
Added test: 79c8c9b6a5323a306834366a4f579fa4763bf133

2024-03-12 08:16 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    address public constant REWARD_TOKEN = 0x5575552988A3A80504bBaeB1311674fCFd40aD4B;
Updated: https://github.com/Sperax/Demeter-Protocol/commit/e911d1cdc3ad6342f3608aa62409f52d02072727

2024-03-12 08:16 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    string public constant CAMELOT_FARM_ID = "Demeter_Camelot_v1";
Removed: https://github.com/Sperax/Demeter-Protocol/commit/e911d1cdc3ad6342f3608aa62409f52d02072727

2024-03-12 08:28 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    error FarmNotSupported();
Removed: https://github.com/Sperax/Demeter-Protocol/commit/e911d1cdc3ad6342f3608aa62409f52d02072727

2024-03-12 08:28 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    error InvalidFarm();
Removed: https://github.com/Sperax/Demeter-Protocol/commit/e911d1cdc3ad6342f3608aa62409f52d02072727

2024-03-12 08:28 UTC, parv3213 commented on contracts/rewarder/RewarderFactory.sol
> +    /// @param _rwdToken Address of the reward token for which the rewarder is to be dpeloyed.
```suggestion
    /// @param _rwdToken Address of the reward token for which the rewarder is to be deployed.
```

2024-03-12 08:28 UTC, parv3213 commented on contracts/rewarder/RewarderFactory.sol
> +        rewarder = address(rewarderInstance);
```suggestion
        rewarder = Clones.clone(rewarderImplementation);
        Rewarder(rewarder).initialize(_rwdToken, oracle, msg.sender);
```

2024-03-12 08:28 UTC, parv3213 commented on contracts/Farm.sol
> +        return rewardTokens;
Oh correct. Then we can make `rewardTokens` internal.

2024-03-12 09:29 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateRewardConfig(address _farm, FarmRewardConfigParams memory _rewardConfig) external onlyOwner {
I do not think it is needed because:
1. It is an onlyOwner function.
2. Owner will not call a suspicious self calling contract for exploitation because his funds/ rewards will be at stake.
3. Even if he does, he will lose funds and he will be the owner of the contract and responsible for his actions.

Adding nonReentrant will only add gas cost which is not required.

2024-03-12 09:36 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function calibrateRewards(address _farm) public returns (uint256 rewardsToSend) {
I do not think it is needed, if you can think of a scenario let us discuss as this function is already very gas intensive.

2024-03-12 09:36 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function getTokenAmounts(address _farm) public view returns (address[] memory assets, uint256[] memory amounts) {
I do not think it is needed, it is an external view function so does not affect anything.

2024-03-12 09:43 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateTokenManagerInFarm(address _farm, address _newManager) external onlyOwner {
Updated: 6f18870a5344d1af6260d5f6837ef90e75e84e5b

2024-03-12 10:08 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +    address public REWARD_TOKEN;
It is there because we have not given the functionality to update reward token, it is not declared as constant or immutable because it is set in the initializer and not a constructor. This is to communicate that this variable cannot be updated with the naming convention.

2024-03-12 10:09 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateRewardConfig(address _farm, FarmRewardConfigParams memory _rewardConfig) external onlyOwner {
Let's not take such risks. Even the owner can make mistakes.

2024-03-12 10:11 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function calibrateRewards(address _farm) public returns (uint256 rewardsToSend) {
Let's not take such risks. Even the owner can make mistakes.

2024-03-12 10:11 UTC, arcantheon commented on contracts/rewarder/RewarderFactory.sol
> +    /// @notice Contructor of this contract.
Updated: 4f50d3d33d05ec70b6d664ffd36e0d21d0f6866f

2024-03-12 10:11 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +    }
Updated: 4f50d3d33d05ec70b6d664ffd36e0d21d0f6866f

2024-03-12 10:11 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +        totalRewardRate += _newRewardRate;
Updated: 4f50d3d33d05ec70b6d664ffd36e0d21d0f6866f

2024-03-12 10:11 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    /// @param _noLockupRewardPer Reward percentage to be allocated to no lockup fund
Updated: 4f50d3d33d05ec70b6d664ffd36e0d21d0f6866f

2024-03-12 10:11 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +            _setRewardRate(_farm, rewardRate, farmRewardConfig.noLockupRewardPer);
Updated: 4f50d3d33d05ec70b6d664ffd36e0d21d0f6866f

2024-03-12 10:12 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +            rewardsToSend = (rewardRate * REWARD_PERIOD);
Updated: 4f50d3d33d05ec70b6d664ffd36e0d21d0f6866f

2024-03-12 10:12 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +                (((farmRewardConfig.apr * totalValue) / (APR_PRECISION * 100)) / 365 days) * _priceData.precision
Updated: 4f50d3d33d05ec70b6d664ffd36e0d21d0f6866f

And 100 is a denominator, like if we want 4% of totalValue, the formula would be (totalValue * 4) / 100.

2024-03-12 10:12 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +            IOracle.PriceData memory _priceData;
Updated: 4f50d3d33d05ec70b6d664ffd36e0d21d0f6866f

2024-03-12 10:13 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function getTokenAmounts(address _farm) public view returns (address[] memory assets, uint256[] memory amounts) {
Yup makes sense. I am not sure why I added this comment.

2024-03-12 10:22 UTC, TechnoGeek01 commented on contracts/utils/TokenUtils.sol
> +            IUniswapV3Utils(_uniUtils).getAmountsForLiquidity(sqrtPriceX96, _tickLower, _tickUpper, uint128(_liquidity));
We can use twap instead of spot price.

2024-03-12 17:19 UTC, YashP16 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateRewardConfig(address _farm, FarmRewardConfigParams memory _rewardConfig) external onlyOwner {
Yeah I agree with Parv on this, even though its only owner [can be other people in public as well, not only us] might make a mistake.

2024-03-12 17:37 UTC, YashP16 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function calibrateRewards(address _farm) public returns (uint256 rewardsToSend) {
Since we are calling calibrate rewards from the updateRewardConfig, I think you will have to create an internal function to resolve things

2024-03-13 06:47 UTC, parv3213 commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +                (((farmRewardConfig.apr * totalValue) / (APR_PRECISION * 100)) / 365 days) * _priceData.precision
Gotcha

2024-03-13 06:49 UTC, parv3213 commented on contracts/rewarder/Rewarder.sol
> +    address public REWARD_TOKEN;
Okay, make sense.

2024-03-13 14:12 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +        FarmRewardConfig memory farmRewardConfig = farmRewardConfigs[_farm];
I have attached the gas reports, in this case, using memory is cheaper.

![Screenshot 2024-03-13 at 18 44 15](https://github.com/Sperax/Demeter-Protocol/assets/140178288/db2e1c91-45bd-4938-a3a6-2245b775d4b6)
![Screenshot 2024-03-13 at 18 44 34](https://github.com/Sperax/Demeter-Protocol/assets/140178288/45653bd2-b91f-4878-856c-37f49f68bd75)

2024-03-13 14:29 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function calibrateRewards(address _farm) public returns (uint256 rewardsToSend) {
Added: 7d45f59c7ced40955d5052cd221db38d32cc9a2e

2024-03-13 14:30 UTC, arcantheon commented on contracts/rewarder/FixedAPRRewarderSPA.sol
> +    function updateRewardConfig(address _farm, FarmRewardConfigParams memory _rewardConfig) external onlyOwner {
Added: 7d45f59c7ced40955d5052cd221db38d32cc9a2e

2024-03-13 14:30 UTC, arcantheon commented on contracts/Farm.sol
> +        return rewardTokens;
Done: 7d45f59c7ced40955d5052cd221db38d32cc9a2e

2024-03-14 06:59 UTC, arcantheon commented on contracts/utils/TokenUtils.sol
> +            IUniswapV3Utils(_uniUtils).getAmountsForLiquidity(sqrtPriceX96, _tickLower, _tickUpper, uint128(_liquidity));
Added: https://github.com/Sperax/Demeter-Protocol/commit/3fb287aca6d3ac977284f3133f4a1c6cc84d2dc7

2024-03-14 07:06 UTC, TechnoGeek01 commented on contracts/utils/TokenUtils.sol
> +            IUniswapV3Utils(_uniUtils).getAmountsForLiquidity(sqrtPriceX96, _tickLower, _tickUpper, uint128(_liquidity));
It's resolved for Uni V3 (getUniV3TokenAmounts). But in Uni V2 (getUniV2TokenAmounts) it's still spot price as we are using the current reserves.

2024-03-14 07:31 UTC, TechnoGeek01 commented on contracts/utils/TokenUtils.sol
> +        (address pair,,,,,,,) = INFTPool(_nftContract).getPoolInfo();
In Uni V2 we don't have any nft contract right. This is for Camelot V2. How this also works for Uni V2?

2024-03-15 07:46 UTC, arcantheon commented on contracts/utils/TokenUtils.sol
> +            IUniswapV3Utils(_uniUtils).getAmountsForLiquidity(sqrtPriceX96, _tickLower, _tickUpper, uint128(_liquidity));
We are going to skip that for now.

2024-03-15 12:35 UTC, parv3213 commented on test/rewarder/LegacyFarmRewarder.t.sol
> +            console.log("* Total rwdRate    : %s", legacyRewarder.totalRewardRate());
Let's remove these consoles.

2024-03-17 06:26 UTC, YashP16 approved these changes

2024-03-18 07:09 UTC, merged