Camelot V3
Sperax/Demeter-Protocol pull request #52
Opened 2024-03-03 06:25 UTC by TechnoGeek01

- [x] Testing

Some important points to be considered:-
* The tickspacing of pools is not immutable.
* If tickspacing is changed in a way that either of our tickUpper and tickLower are not divisible by this new tickspacing, users will not be able to mint new positions adhering to our farm ticks and they will also not be able to increase liquidity of their current positions.
* We can reduce risk by choosing tickLower and tickUpper as (highly divisible numbers and there should be more common divisors/factors between the two numbers) in our farm tick requirement. And ofcourse both the numbers should be divisible by the tickspacing of the pool at the time of farm launch.
* Camelot V3 pools can set tickspacing upto 500. 

Other differences from Uniswap V3 -> https://docs.algebra.finance/algebra-integral-documentation/algebra-integral-technical-reference/integration-process/migration-from-uniswapv3

2024-03-11 10:53 UTC, parv3213 commented on contracts/e721-farms/camelotV3/CamelotV3Farm.sol
Can you remove fee-related checks from UniV3Farm as well?

2024-03-11 11:01 UTC, parv3213 approved these changes

2024-03-11 11:01 UTC, parv3213 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +    // Users will not be able to increaseLiquidity of their current positions if the pool’s tickSpacing is changed.
What do we want to do with this test?

2024-03-11 11:02 UTC, TechnoGeek01 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +    // Users will not be able to increaseLiquidity of their current positions if the pool’s tickSpacing is changed.
I will remove it!

2024-03-11 11:04 UTC, parv3213 commented on contracts/e721-farms/camelotV3/CamelotV3Farm.sol
Oh, I see you have done that in another PR. Alright 👍

2024-03-11 11:07 UTC, TechnoGeek01 commented on contracts/e721-farms/camelotV3/CamelotV3Farm.sol
I have worked on similar changes in this pr https://github.com/Sperax/Demeter-Protocol/pull/53

2024-03-11 11:13 UTC, TechnoGeek01 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +    // Users will not be able to increaseLiquidity of their current positions if the pool’s tickSpacing is changed.
fixed in [6db59ac](https://github.com/Sperax/Demeter-Protocol/pull/52/commits/6db59acf6d8f4b49118e4f03e4d0271c015c6c5e)

2024-03-19 06:21 UTC, parv3213 commented on contracts/e721-farms/camelotV3/interfaces/ICamelotV3NonfungiblePositionManagerUtils.sol
> +interface INFPMUtils {
Rename according to filename?

2024-03-19 06:22 UTC, parv3213 commented on package.json
> +    "@cryptoalgebra/v1.9-periphery": "^1.0.1",
Are you using both of these packages?

2024-03-19 06:23 UTC, parv3213 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        emit log_named_uint("amount0", amount[0]);
Instead of logging can we assert these?

2024-03-19 07:13 UTC, TechnoGeek01 commented on package.json
> +    "@cryptoalgebra/v1.9-periphery": "^1.0.1",
only the directional fee package is required. Will remove it.

2024-03-19 07:18 UTC, TechnoGeek01 commented on package.json
> +    "@cryptoalgebra/v1.9-periphery": "^1.0.1",
fixed in [3060b15](https://github.com/Sperax/Demeter-Protocol/pull/52/commits/3060b1514c8f8f56196f4b09aca7dc9145e2bacb)

2024-03-19 07:29 UTC, TechnoGeek01 commented on contracts/e721-farms/camelotV3/interfaces/ICamelotV3NonfungiblePositionManagerUtils.sol
> +interface INFPMUtils {
fixed in [1560fd6](https://github.com/Sperax/Demeter-Protocol/pull/52/commits/1560fd6600dcbd1aa5e684e113d4cc5a125fc134)

2024-03-19 07:30 UTC, TechnoGeek01 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        emit log_named_uint("amount0", amount[0]);
These are complicated to assert as the price keeps changing as per market conditions.

2024-03-19 07:33 UTC, parv3213 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        emit log_named_uint("amount0", amount[0]);
We must assert, logging is of no use. Maybe assert based on the formula used in getTokenAmounts?

2024-03-19 09:08 UTC, TechnoGeek01 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        emit log_named_uint("amount0", amount[0]);
fixed in [a1d1879](https://github.com/Sperax/Demeter-Protocol/pull/52/commits/a1d187951c298576458f9dbfbeaf5c2ca1da3434)

2024-03-20 07:27 UTC, YashP16 requested changes

2024-03-20 07:27 UTC, YashP16 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        uint256 depositAmount1 = 1e3 * 10 ** ERC20(DAI).decimals();
This chunk of code could be a single function that mints token and returns tokenId

2024-03-20 07:27 UTC, YashP16 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        CamelotV3Farm(farmProxy).initialize({
Update the comment to highlight the exact line that should fail

2024-03-20 07:49 UTC, TechnoGeek01 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        CamelotV3Farm(farmProxy).initialize({
There were some redundant cases in this test case. Removed them.

fixed in [a36bd25](https://github.com/Sperax/Demeter-Protocol/pull/52/commits/a36bd2578e2d5bbb0f1a54a6fa04d99e9fa245d0)

2024-03-20 07:50 UTC, TechnoGeek01 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        CamelotV3Farm(farmProxy).initialize({
Same mistake done in Uniswap V3 test cases as well. Shall I remove them from there as well?

2024-03-20 07:58 UTC, TechnoGeek01 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        uint256 depositAmount1 = 1e3 * 10 ** ERC20(DAI).decimals();
fixed in [6929aef](https://github.com/Sperax/Demeter-Protocol/pull/52/commits/6929aef2c3bb0efcb59196a67bc0e201b30338e8)

2024-03-20 08:00 UTC, TechnoGeek01 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        uint256 depositAmount1 = 1e3 * 10 ** ERC20(DAI).decimals();
We can do this in UniV3 test cases as well. Shall I do this?

2024-03-20 08:40 UTC, YashP16 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        uint256 depositAmount1 = 1e3 * 10 ** ERC20(DAI).decimals();
Lets do it in another PR later

2024-03-20 08:41 UTC, YashP16 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
> +        CamelotV3Farm(farmProxy).initialize({
Lets do it in another PR later

2024-03-20 08:41 UTC, YashP16 approved these changes

2024-03-20 09:09 UTC, arcantheon commented on contracts/e721-farms/camelotV3/CamelotV3Farm.sol
> +    function initialize(
Convert it to struct input like this: https://github.com/Sperax/Demeter-Protocol/blob/a8cfd61c98a9ebce56907a86f74913d0e623320f/contracts/e721-farms/uniswapV3/UniV3Farm.sol#L101

2024-03-20 09:11 UTC, arcantheon commented on contracts/e721-farms/camelotV3/CamelotV3Farm.sol
> +    function _validateTickRange(int24 _tickLower, int24 _tickUpper) private view {
Please add natspec

2024-03-20 09:15 UTC, arcantheon requested changes
Added two comments

2024-03-20 10:12 UTC, TechnoGeek01 commented on contracts/e721-farms/camelotV3/CamelotV3Farm.sol
> +    function initialize(
fixed in [edc3506](https://github.com/Sperax/Demeter-Protocol/pull/52/commits/edc350625863a6f48d4bacc0d8aa548d3dc18ddf)

2024-03-20 10:18 UTC, TechnoGeek01 commented on contracts/e721-farms/camelotV3/CamelotV3Farm.sol
> +    function _validateTickRange(int24 _tickLower, int24 _tickUpper) private view {
fixed in [16b42db](https://github.com/Sperax/Demeter-Protocol/pull/52/commits/16b42dbb6f2883cd2b2ba03d56aef24dae39e2ab)

2024-03-20 10:25 UTC, arcantheon approved these changes

2024-03-20 10:44 UTC, merged