optimized Uni V3 claim fee
Sperax/Demeter-Protocol pull request #54
Opened 2024-03-18 07:59 UTC by TechnoGeek01

For getting unclaimed accrued fees of a position to display in front-end we can do a static call on nft position manager's collect function with the required tokenId, amount0max and amount1max as uint128(max) (2^128 - 1).

Increase deposit or decrease deposit won't affect our new fee collection logic. reviewed it.

2024-03-19 06:17 UTC, parv3213 commented on test/e721-farms/uniswapv3/UniV3Farm.t.sol
> +        vm.expectEmit(true, false, false, false, address(lockupFarm));
Let's assert all these params. We can use this 
```
(uint256 amt0, uint256 amt1) = IUniswapV3Utils(uniswapUtils).fees(pm, tokenId);
```

2024-03-19 06:17 UTC, parv3213 approved these changes

2024-03-19 07:07 UTC, TechnoGeek01 commented on test/e721-farms/uniswapv3/UniV3Farm.t.sol
> +        vm.expectEmit(true, false, false, false, address(lockupFarm));
Yeah, since we reintroduced uniswap utils we can do this assert.

2024-03-19 07:07 UTC, TechnoGeek01 commented on test/e721-farms/uniswapv3/UniV3Farm.t.sol
> +        vm.expectEmit(true, false, false, false, address(lockupFarm));
Fixed in [76fa3da](https://github.com/Sperax/Demeter-Protocol/pull/54/commits/76fa3dadc3d37cdc08dd40be7ea3aba336aefb66)

2024-03-19 12:56 UTC, arcantheon commented on test/e721-farms/uniswapv3/UniV3Farm.t.sol
> +import "../../../contracts/e721-farms/uniswapV3/interfaces/IUniswapV3Utils.sol";
Use named imports on lines 25-27

2024-03-19 12:56 UTC, arcantheon commented on test/e721-farms/uniswapv3/UniV3Farm.t.sol
>          UniV3Farm(lockupFarm).claimUniswapFee(depositId);
Assertions missing

2024-03-19 12:57 UTC, arcantheon requested changes
2 comments added

2024-03-19 12:58 UTC, parv3213 commented on test/e721-farms/uniswapv3/UniV3Farm.t.sol
> +import "../../../contracts/e721-farms/uniswapV3/interfaces/IUniswapV3Utils.sol";
Should be fine in testcases.

2024-03-19 13:15 UTC, TechnoGeek01 commented on test/e721-farms/uniswapv3/UniV3Farm.t.sol
>          UniV3Farm(lockupFarm).claimUniswapFee(depositId);
fixed in [7c12912](https://github.com/Sperax/Demeter-Protocol/pull/54/commits/7c129125969ea553e5f1584b72a7aa411c3b4179)

2024-03-20 06:24 UTC, TechnoGeek01 commented on test/e721-farms/uniswapv3/UniV3Farm.t.sol
> +import "../../../contracts/e721-farms/uniswapV3/interfaces/IUniswapV3Utils.sol";
fixed in [1c1620a](https://github.com/Sperax/Demeter-Protocol/pull/54/commits/1c1620a1d2cc4f064aa86cc4ac93abbb2ec8d51d)

2024-03-20 07:08 UTC, YashP16 approved these changes

2024-03-20 07:13 UTC, arcantheon approved these changes

2024-03-20 07:20 UTC, merged