Audit Fixes: QS-1
Sperax/Demeter-Protocol pull request #61
Opened 2024-06-18 08:05 UTC by parv3213

-  This bug was introduced in https://github.com/Sperax/Demeter-Protocol/pull/21/
- Add `farmStartTime` in place of `lastFundUpdateTime`
- `_getRewardAccrualTimeElapsed` will return 0 if `block.timestamp > farmStartTime` or `lastFundUpdateTime = 0`
- Change logic when `lastFundUpdateTime` is updated. This is added to fix problems in UniV3ActiveFarm
- Fixed testcases for the changes
<img width="969" alt="Screenshot 2024-06-18 at 1 31 54 PM" src="https://github.com/Sperax/Demeter-Protocol/assets/45873074/d22f7975-d9ad-45dd-9c51-97ce507f6db3">

2024-06-18 18:32 UTC, arcantheon requested changes

2024-06-18 18:32 UTC, arcantheon commented on test/Farm.t.sol
> +    function testFuzz_Deposit_Before_Farm_StartTime(bool lockup) public {
This test is not relevant and sufficient, `lastFundUpdateTime` was always set to farmStartTime. The problem was _getRewardAccrualTimeElapsed returning unrealistically high value which user could exploit to get huge rewards. We should do a test where user is not getting any rewards before farm starts.

2024-06-18 18:32 UTC, arcantheon commented on test/Farm.t.sol
> +    function testFuzz_Deposit_Before_Farm_StartTime(bool lockup) public {
We should first re create this by using this scenario and calling `computeRewards()` and then after the fix we can check that computeRewards should return 0

2024-06-19 08:29 UTC, parv3213 commented on test/Farm.t.sol
> +    function testFuzz_Deposit_Before_Farm_StartTime(bool lockup) public {
The newly added test checks if _getRewardAccrualTimeElapsed is zero in this case. The anomaly arose because the earlier code would return a value greater than zero. The test confirms _getRewardAccrualTimeElapsed is zero by verifying that lastFundUpdateTime is unchanged, which would change if the elapsed time was greater than zero, [here](https://github.com/Sperax/Demeter-Protocol/blob/dev/contracts/Farm.sol#L651).

If this first condition for ensuring rewards is correct, we need not write more code to compare the ensured rewards.

2024-06-19 11:59 UTC, arcantheon approved these changes

2024-06-20 07:26 UTC, YashP16 approved these changes

2024-06-20 07:28 UTC, YashP16 commented
@parv3213 , Aren't we overriding this function `_getRewardAccrualTimeElapsed` in the UniV3ActiveLiquidity farms ?

2024-06-20 07:30 UTC, parv3213 commented
> _getRewardAccrualTimeElapsed

We are.

2024-06-20 08:15 UTC, YashP16 commented
On further analysis we discovered some other issues with the UniV3ActiveLiquidityFarm. 
* UniV3ActiveLiquidity farm does not consider the farmStartTime at all. 

Resolutions: 
* Add the `farmStartTime` variable to track the rewardAccrual
* Always update the `lastFundUpdateTime` when `_updateFarmRewardData()` is called

2024-06-20 14:38 UTC, arcantheon commented on contracts/Farm.sol
> +        farmStartTime = _farmStartTime;
It is better to call `updateFarmStartTime` here instead of setting the variable here.

2024-06-20 14:39 UTC, arcantheon requested changes
Left review comment

2024-06-20 14:41 UTC, arcantheon commented on contracts/Farm.sol
> -            _updateLastRewardAccrualTime();
We should update the comment on line 622 and 623 as we have moved this outside of this if statement

2024-06-20 14:42 UTC, arcantheon requested changes
Left two review comments

2024-06-21 06:34 UTC, parv3213 commented on contracts/Farm.sol
> +        farmStartTime = _farmStartTime;
I don't think we can do that. `updateFarmStartTime` has more complicated logic, and is also overidden in other files.

2024-06-21 06:39 UTC, parv3213 commented on contracts/Farm.sol
> -            _updateLastRewardAccrualTime();
Fixed in https://github.com/Sperax/Demeter-Protocol/pull/61/commits/e618a4b63c2c267aa27605d455553002a745fa8e

2024-06-21 06:41 UTC, arcantheon approved these changes

2024-06-21 07:09 UTC, YashP16 requested changes

2024-06-21 07:09 UTC, YashP16 commented on contracts/Farm.sol
> +        if (farmStartTime > block.timestamp) {
@parv3213 , we need to also check for the case where lastFundUpdateTime is 0 ?

2024-06-21 07:09 UTC, YashP16 commented on contracts/features/ExpirableFarm.sol
> +        uint256 _currentFarmStartTime = farmStartTime;
Make the naming of func variables consistent 
should be `currentFarmStartTime`

2024-06-21 07:09 UTC, YashP16 commented on contracts/Farm.sol
> +        if (farmStartTime > block.timestamp) {
Consider a case where the farm is created with a timestamp in future, but there is no action on the farm till the farm starts.

2024-06-21 07:17 UTC, parv3213 commented on contracts/features/ExpirableFarm.sol
> +        uint256 _currentFarmStartTime = farmStartTime;
fixed in https://github.com/Sperax/Demeter-Protocol/pull/61/commits/0a351a1a5d27b7ae9d30c067a8858e6c3b8209c4

2024-06-21 07:17 UTC, parv3213 commented on contracts/Farm.sol
> +        if (farmStartTime > block.timestamp) {
fixed in https://github.com/Sperax/Demeter-Protocol/pull/61/commits/bbb84e2e57456a7ce4918f77293d080aa174411a

2024-06-21 07:24 UTC, YashP16 approved these changes

2024-06-21 07:24 UTC, merged