Audit Fixes: QS-9
Sperax/Demeter-Protocol pull request #63
Opened 2024-06-18 10:08 UTC by parv3213

- Privileged deployers and registered farm deployers are separate. Privileged deployers receive a discount on farm creation fees, whereas registered farm deployers are authorized addresses for farm creation.
To avoid this confusion in the future, we will rename isPrivilegedDeployer to isPrivilegedUser for clarity.

<img width="1179" alt="Screenshot 2024-06-18 at 3 37 35 PM" src="https://github.com/Sperax/Demeter-Protocol/assets/45873074/7305b1ad-965a-4c26-abdf-b61bdfd2d2ab">

2024-06-18 18:29 UTC, arcantheon commented on contracts/FarmRegistry.sol
> +    /// @notice Function to add/remove privileged Users.
```suggestion
    /// @notice Function to add/remove privileged User.
```

2024-06-18 18:30 UTC, arcantheon commented on contracts/FarmRegistry.sol
> +    function updatePrivilege(address _userAddress, bool _privilege) external onlyOwner {
```suggestion
    function updatePrivilege(address _user, bool _privilege) external onlyOwner {
```

2024-06-18 18:31 UTC, arcantheon commented on contracts/FarmRegistry.sol
>      function getFeeParams(address _deployerAccount) external view returns (address, address, uint256, uint256) {
We should rename this as well to just `_user`

2024-06-18 18:35 UTC, arcantheon approved these changes
Requested changes

2024-06-18 18:36 UTC, arcantheon requested changes
Added review comments

2024-06-19 11:44 UTC, arcantheon commented on contracts/FarmRegistry.sol
> +        if (isPrivilegedUser[_userAddress] == _privilege) {
```suggestion
        if (isPrivilegedUser[_user] == _privilege) {
```

2024-06-19 11:44 UTC, arcantheon commented on contracts/FarmRegistry.sol
> +        isPrivilegedUser[_userAddress] = _privilege;
```suggestion
        isPrivilegedUser[_user] = _privilege;
```

2024-06-19 11:45 UTC, arcantheon commented on contracts/FarmRegistry.sol
> +        emit PrivilegeUpdated(_userAddress, _privilege);
```suggestion
        emit PrivilegeUpdated(_user, _privilege);
```

2024-06-20 10:07 UTC, YashP16 commented on contracts/FarmRegistry.sol
> +        if (isPrivilegedUser[_userAddress] == _privilege) {
Why did this not throw an error on compilation 🤔

2024-06-20 11:11 UTC, parv3213 commented on contracts/FarmRegistry.sol
> +        emit PrivilegeUpdated(_userAddress, _privilege);
Fixed in https://github.com/Sperax/Demeter-Protocol/pull/63/commits/58ed6577d00b4f8f411bbb759c3086247f054ffa

2024-06-20 11:12 UTC, parv3213 commented on contracts/FarmRegistry.sol
> +        isPrivilegedUser[_userAddress] = _privilege;
Fixed in https://github.com/Sperax/Demeter-Protocol/pull/63/commits/58ed6577d00b4f8f411bbb759c3086247f054ffa

2024-06-20 11:12 UTC, parv3213 commented on contracts/FarmRegistry.sol
> +        if (isPrivilegedUser[_userAddress] == _privilege) {
Fixed in https://github.com/Sperax/Demeter-Protocol/pull/63/commits/58ed6577d00b4f8f411bbb759c3086247f054ffa

2024-06-21 06:32 UTC, arcantheon commented on contracts/FarmRegistry.sol
> +        if (isPrivilegedUser[_userAddress] == _privilege) {
@YashP16 , maybe @parv3213 pushed comment suggestion from here instead of from the IDE. And that's how the changes in the implementation were missed.

2024-06-21 06:34 UTC, arcantheon approved these changes

2024-06-21 07:11 UTC, YashP16 approved these changes

2024-06-21 07:28 UTC, merged