Audit Fixed QS-14
Sperax/Demeter-Protocol pull request #72
Opened 2024-06-20 15:08 UTC by arcantheon

Fixed repititive inheritence.

![Screenshot 2024-06-20 at 20 37 55](https://github.com/Sperax/Demeter-Protocol/assets/140178288/d09526bd-7695-4363-8795-63bf8e823f38)

2024-06-24 14:53 UTC, YashP16 requested changes
@arcantheon,
Let's remove ExpirableFarm from the OperableDeposit and resolve these dependencies at the topmost level only.

2024-06-25 10:35 UTC, arcantheon commented
> @arcantheon, Let's remove ExpirableFarm from the OperableDeposit and resolve these dependencies at the topmost level only.

Done: e8fa68ca33fa89234f8b9a315f3532a402616f62

2024-06-25 11:20 UTC, parv3213 commented on contracts/e20-farms/E20Farm.sol
> +    function recoverERC20(address _token) public virtual override onlyOwner nonReentrant {
If instead of overriding this we override `_recoverE20` we can get way without making this function public

2024-06-25 11:30 UTC, parv3213 commented on contracts/rewarder/Rewarder.sol
> +    constructor() Ownable(msg.sender) {
Let's handle this change in QS-10?

2024-06-25 11:39 UTC, parv3213 commented on contracts/Farm.sol
Actually even this change should be part of QS-10. Btw, it is already there in QS-10

2024-06-25 11:41 UTC, parv3213 commented on contracts/e20-farms/E20Farm.sol
> +    ) public {
Even this function we are making `public` from `external`

2024-06-25 11:50 UTC, parv3213 commented on contracts/e20-farms/E20Farm.sol
> +    ) public {
Here also can we make `initialize` in E20Farm an internal function? And call this internal function in top layer farms? Also, overriding does not makes sense here both functions serves a different purpose.

2024-06-25 11:54 UTC, parv3213 commented on contracts/rewarder/Rewarder.sol
> +    constructor() Ownable(msg.sender) {
https://github.com/Sperax/Demeter-Protocol/pull/72#discussion_r1652667664

2024-06-25 11:56 UTC, parv3213 commented on contracts/Farm.sol
@arcantheon I have pushed a commit to remove this and related code in [cb6fb02](https://github.com/Sperax/Demeter-Protocol/pull/72/commits/cb6fb027e25a299542618ee31f3549f850b114c4). Please check and if you feel otherwise we can revert this commit. 
Btw, this commit is, although passing all test, failing a solhint check. I haven't fixed this as we might change some logic based on https://github.com/Sperax/Demeter-Protocol/pull/72#discussion_r1652658741

2024-06-25 13:42 UTC, arcantheon commented on contracts/e20-farms/E20Farm.sol
> +    function recoverERC20(address _token) public virtual override onlyOwner nonReentrant {
Good point, done: da7d7f2914e0beec9037c71e1f95ebe8e2f39aee

2024-06-25 13:45 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +    constructor() Ownable(msg.sender) {
If we merge QS10 first, this won't be reflecting as a change anymore.

2024-06-25 13:45 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +    constructor() Ownable(msg.sender) {
Reverting pushed changes would waste time and can introduce bugs.

2024-06-25 13:46 UTC, arcantheon commented on contracts/Farm.sol
Makes sense

2024-06-25 13:48 UTC, parv3213 commented on contracts/Farm.sol
>      function recoverERC20(address _token) external virtual onlyOwner nonReentrant {
```suggestion
    function recoverERC20(address _token) external onlyOwner nonReentrant {
```

2024-06-25 14:19 UTC, arcantheon commented on contracts/e20-farms/E20Farm.sol
> +    ) public {
Done: c9acb2278965b61a42fe9360652743b8317cd48b

2024-06-25 14:38 UTC, YashP16 approved these changes
Changes look good

2024-06-25 14:43 UTC, parv3213 approved these changes
Looks good 👍 .
There are two solhint warnings introduced with these changes. Can you please fix them as well.

2024-06-26 07:11 UTC, merged