Audit Fixes QS-10
Sperax/Demeter-Protocol pull request #75
Opened 2024-06-21 10:14 UTC by arcantheon

Moved initializer modifier from top level farms to Farm.sol's _setupFarm.
And added _disableInitializers() in Rewarder.sol

![Screenshot 2024-06-21 at 15 43 13](https://github.com/Sperax/Demeter-Protocol/assets/140178288/a7989421-342f-401d-848c-5f890bbce7a9)

2024-06-21 10:18 UTC, parv3213 commented
@arcantheon we also want to handle this case-

> Further, as the non-upgradeable version of Ownable is inherited by Rewarder , Rewarder.constructor() stores the deployer address as the owner of the contract. This is also the case in the Farm contract.

2024-06-21 14:00 UTC, arcantheon commented
> @arcantheon we also want to handle this case-
> 
> > Further, as the non-upgradeable version of Ownable is inherited by Rewarder , Rewarder.constructor() stores the deployer address as the owner of the contract. This is also the case in the Farm contract.

Updated here: c1ac258799e022e9d67c734556bbf06cd0bb6c97

2024-06-24 10:57 UTC, parv3213 commented on contracts/rewarder/Rewarder.sol
> +    function _initialize(address _rwdToken, address _oracle, address _admin, address _rewarderFactory)
Question: can we move this inside `initialize`?

2024-06-24 11:01 UTC, parv3213 approved these changes

2024-06-24 11:03 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +    function _initialize(address _rwdToken, address _oracle, address _admin, address _rewarderFactory)
It is there because we call this function from the LegacyRewarder contract. It is commented for now. Will move the modifier in the `initialize`

2024-06-24 12:55 UTC, arcantheon commented on contracts/rewarder/Rewarder.sol
> +    function _initialize(address _rwdToken, address _oracle, address _admin, address _rewarderFactory)
As per the discussion, moved initializer above : bf20692ea8402f6c3d2cd3663db1060fb18687e1

2024-06-24 14:29 UTC, YashP16 commented on test/rewarder/LegacyFarmRewarder.t.sol
>  // SPDX-License-Identifier: MIT
@arcantheon, lets just create a for branch from dev and delete LegacyFarmRewarder and related test file

2024-06-25 11:46 UTC, parv3213 requested changes
Need to revert all changes removing `ExpirableFarm` from the top layer farm. Based on the changes based in #72

2024-06-26 08:15 UTC, parv3213 approved these changes

2024-06-26 09:41 UTC, YashP16 approved these changes

2024-06-26 09:41 UTC, merged