Audit Fixes QS-S-2
Sperax/Demeter-Protocol pull request #78
Opened 2024-06-24 13:21 UTC by parv3213

1. We have implemented the recommended change.
2. We do agree that the implementation for these functions are quite similar, but further abstraction would result into gas cost increase for the transactions involving these functions. 
3. Merging computeRewards() and _updateFarmRewardData() is very complicated and might add-up unnecessary gas cost post abstraction. 
4. We have made deployerList and farms internal. We have kept the functions for making it easier to fetch data on frontend if required.
5. CamelotV3 and UniswapV3 farms involve different interfaces, we can try abstracting them, however it might result in unwanted complexities. Due to time constraints we will skip it for time being. 

<img width="1051" alt="Screenshot 2024-06-24 at 6 51 03 PM" src="https://github.com/Sperax/Demeter-Protocol/assets/45873074/c2427640-45ea-43c7-8eaa-403e1d38cc3f">

2024-06-24 13:27 UTC, arcantheon commented on contracts/features/OperableDeposit.sol
> -    uint256 public constant PRECISION = 1e18;
Maybe update the name to PRECISION in FarmStorage because PREC is a little confusing to outsiders and not so clear.

2024-06-24 13:27 UTC, arcantheon requested changes
Review comment posted

2024-06-25 07:00 UTC, parv3213 commented on contracts/features/OperableDeposit.sol
> -    uint256 public constant PRECISION = 1e18;
Fixed in [6b82c96](https://github.com/Sperax/Demeter-Protocol/pull/78/commits/6b82c96167c1d139bec9f6d727eccad7628fd57d)

2024-06-25 14:58 UTC, YashP16 approved these changes

2024-06-25 14:59 UTC, YashP16 commented
@parv3213, Lets address all the other points here itself.

2024-06-26 08:21 UTC, arcantheon approved these changes

2024-06-26 10:17 UTC, merged