Move claimPoolFee from UniV3Farm and CamelotV3Farm to E721Farm
Sperax/Demeter-Protocol pull request #87
Opened 2024-07-01 15:16 UTC by arcantheon

2024-07-02 11:35 UTC, YashP16 requested changes

2024-07-02 11:35 UTC, YashP16 commented on test/e721-farms/camelotV3/CamelotV3Farm.t.sol
We should move the common claimPoolFee tests to a features test file and import test cases from there ?

2024-07-02 11:57 UTC, parv3213 approved these changes

2024-07-03 13:40 UTC, YashP16 approved these changes
We decided to optimize test cases later.

2024-07-03 13:40 UTC, merged